name = "ReasBook"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["ReasBook"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3
linter.style.longLine = false
linter.style.emptyLine = false
linter.style.cdot = false
linter.style.maxHeartbeats = false
linter.unnecessarySimpa = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.26.0-rc2"

[[lean_lib]]
name = "ReasBook"

[[lean_lib]]
name = "Books"

[[lean_lib]]
name = "Papers"
